### ISSUE TITLE
node js usage?

### ISSUE THREAD

**Issue by l4km47** [Jack-Barry/get-file-properties#1]
how can i use that with node js

**Comment by Jack-Barry** [comment]
It's for getting file properties from Windows files into your Node scripts.

So if you need to get something like the Version metadata from an executable, you can do it with this as long as `wmic.exe` is installed on the machine and in the `PATH`.

It's a fairly trivial tool, mainly just does the work of parsing output from `wmic.exe` for you and turning it into an object. I'm open to PRs to extend it to work with macOS and Linux though.

Docs for how to install and use are here: [`README.md`](https://github.com/Jack-Barry/get-file-properties/blob/d5f070fe8e6b2a1e07d74bf80e33f2e9638aee76/README.md)

**Comment by l4km47** [comment]
thanks
